name: riard
favicon: null
layout_spectrum: 0.8003295508679003
typography_spectrum: 0.40932029904797673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6730031834449619
  lightness: 0.6401428987737745
  saturation: 0.40590656013228
  rhythmicContrast: 0.171798478346318
purpose: []
